version: "3.7"
services:
  desecurity:
    container_name: desecurity
    build: ./
    image: local/desecurity:latest
    restart: unless-stopped
    volumes:
      - $DATA_FOLDER:/data
    environment:
      - TZ=Europe/Madrid
      - CAM_USER=$CAM_USER
      - CAM_PASSWORD=$CAM_PASSWORD
      - CAM_IP=$CAM_IP
      - CAM_PORT=$CAM_PORT
      - RETENTION_PERIOD=$RETENTION_PERIOD
      - DATA_FOLDER=/data
  security-fileserve:
    container_name: security-fileserve
    image: halverneus/static-file-server:v1.8.6
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - $DATA_FOLDER:/data
    environment:
      - FOLDER=/data
      - TZ=Europe/Madrid
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.desecurity.entrypoints=websecure
      - traefik.http.routers.desecurity.rule=Host(`security.$DOMAIN`)
      - traefik.http.routers.desecurity.tls=true
      - traefik.http.routers.desecurity.tls.certresolver=le
networks:
  traefik:
    name: traefik
    external: true
